### ISSUE TITLE
"Snippets successfully fetched" notification is annoying

### ISSUE THREAD

**Issue by covertbert** [snipsnapdev/snipsnap#25]
"Snippets successfully fetched" notification is kinda annoying. I find any notifications in VSCode annoying unless they're errors though so maybe that's just me...

**Comment by lnikell** [comment]
Thank you for the feedback @covertbert! We will consider removing notification on opening fetch, however, I guess having this for manual fetch via command palette still makes sense and provide good UX.  

What is your overall experience with the extension?

**Comment by covertbert** [comment]
I agree that having feedback for the manual fetch is a good idea!

I guess my feeling about the automatic one is that it appears quite often and so it becomes noise that the brain will eventually just ignore.

Maybe it makes more sense to notify if it fails instead as this is what should matter to the user?

Just ideas anyway, maybe I’m wrong 😊

I love the extension anyway! It just needs TS support for me to really use it but I’ve added my comment about this to the other issue.

**Comment by YoussefZidan** [comment]
> "Snippets successfully fetched" notification is kinda annoying. I find any notifications in VSCode annoying unless they're errors though so maybe that's just me...

I find it useful actually

**Comment by lnikell** [comment]
Today we've discussed that we can add the ability to turn off notification inside Extension configuration, so it will be possible to disable them easily via UI if you find them annoying. If someone would like to be a volunteer to handle this, please let us know.

**Comment by lnikell** [comment]
@covertbert Hey, we added the ability to disable notifications, you can read more about it [here](https://github.com/snipsnapdev/snipsnap-vscode#silent-mode)

**Comment by covertbert** [comment]
Thanks guys, much appreciated!
