### ISSUE TITLE
Snippets not working inbetween <script> of Vue and Nuxt components

### ISSUE THREAD

**Issue by ceafive** [snipsnapdev/snipsnap#34]
I used Snipsnap on a Vue and Nuxt project and I have realised that snippets do not work in the script section of a component. Can you please have a look at this? Thanks. 

Impressive work so far.

**Comment by lnikell** [comment]
@ceafive could you check it now please(fetch latest snippets at first)

**Comment by ceafive** [comment]
@lnikell yes works perfectly now
