### ISSUE TITLE
Native javascript snippets

### ISSUE THREAD

**Issue by ronaldruzicka** [snipsnapdev/snipsnap#38]
Hi, firstly thanks for this awesome project!

I would like to ask, are you also planning to support some native javascript snippets? For example `console.log`, destructuring `const { variable } = obj`, loops and so on. Snippets that are not part of any library just vanilla JS.

I could even create a pull request, I 'm just not sure if that's something that you would like to support as well.

Thanks.

**Comment by lnikell** [comment]
Hi @ronaldruzicka, thank you for the feedback. The update with this change will come today and also it allign with our current roadmap/discussion for v1.1.0.

Stay tuned!

**Comment by lnikell** [comment]
@ronaldruzicka Version 1.0.3 with the support of base javascript snippets added. 
So now you can search by typing `base` keyword. 

![Screen Recording 2020-06-22 at 17 01 07](https://user-images.githubusercontent.com/2697570/85303051-47302900-b4aa-11ea-9a35-c15642d0f7c1.gif)
