### ISSUE TITLE
Add support for groups/folders under "My templates"

### ISSUE THREAD

**Issue by lokecarlsson** [snipsnapdev/snipsnap#94]
Would be great to be able to create folders in "My templates" to group them up.

**Comment by lnikell** [comment]
@lokecarlsson you already have this functionality. Just press pluss and click "Create group". Is it what you're looking for?

https://user-images.githubusercontent.com/2697570/122359325-c0474c80-cf55-11eb-86ca-8547866286fe.mov

**Comment by lokecarlsson** [comment]
Sorry, totally missed that! Awesome, thanks!
